config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "registrations#new", as: :join
  post "join/:join_code", to: "registrations#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  scope module: "sales" do
    scope "sales_channels/:sales_channel_id", as: "sales_channel", constraints: { sales_channel_id: /\d+/ } do
      resources :orders do
        scope module: "orders" do
          resources :positions, except: :show
        end
      end
    end

    resources :plans, except: %i[ new create ] do
      scope module: "plans" do
        resources :consolidations, except: %i[ show new create ]
        resources :groups, only: :index
      end
    end

    resources :sales_plans
  end

  namespace "production" do
    resources :plans, except: :destroy do
      scope module: "plans" do
        get :summary, to: "summaries#index"
        resources :units, controller: "production_units", except: %i[ new create destroy ] do
          scope module: "production_units" do
            resources :batches, except: :destroy do
              get "info", to: "batches#info", on: :member
              get "summary", to: "batches#summary", on: :member

              scope module: "batches" do
                resources :journals, only: :show
                resources :steps, only: %i[ edit create update ]
                resource :packing, except: :destroy do
                  scope module: "packings" do
                    resources :packaged_products, only: %i[ index edit update ] do
                      scope module: "packaged_products" do
                        resources :machineries, except: :show do
                          collection do
                            get "search", to: "machineries#search"
                          end
                        end
                      end
                    end
                  end
                end
                resource :cooking, except: :destroy do
                  scope module: "cookings" do
                    resources :cooked_semi_products, only: %i[ index edit update ]
                  end
                end
                resource :distribution, except: :destroy do
                  scope module: "distributions" do
                    resources :distributed_products, only: %i[ index edit update ] do
                      scope module: "distributed_products" do
                        resource :generation, only: %i[ show new create ] do
                          scope module: "generations" do
                            resources :boxes, only: :index do
                              collection do
                                post :download, to: "boxes#download"
                              end
                            end
                            resources :pallets, only: %i[ index new create ] do
                              collection do
                                post :download, to: "pallets#download"
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end

  scope module: "procurements" do
    resources :supply_orders, except: :destroy do
      collection do
        get "search", to: "supply_orders#search"
      end
    end
    resources :supply_operations do
      scope module: "supply_operations" do
        resources :leftovers, except: :show
      end
    end
    resources :supply_material_assets, only: %i[ index show ] do
      scope module: "supply_material_assets" do
        resources :storages, only: :index
      end
    end
  end

  scope module: "warehouse" do
    scope module: "storages" do
      get "warehousers/search", to: "warehousers#search", as: :warehousers_search
    end

    resources :storages, except: :destroy do
      scope module: "storages" do
        resources :subjects, only: :index
        resources :waybills, only: :index
        resources :zones do
          scope module: "zones" do
            resources :lines do
              scope module: "lines" do
                resources :stacks do
                  scope module: "stacks" do
                    resources :tiers
                  end
                end
              end
            end
          end
        end
        resource :map, only: :show
        resources :warehousers, except: :show
      end
    end
    resources :waybills, only: %i[ index show edit update ] do
      scope module: "waybills" do
        resources :leftovers, only: :index
        resources :qr_scans, only: %i[ index edit update ]
      end
    end
    resources :boxes, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "boxes#location", as: :location
      end
    end
    resources :pallets, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "pallets#location", as: :location
      end
    end
  end

  scope module: "settings" do
    resources :regions, except: :destroy
    resources :sales_channels, except: :destroy
    resources :suppliers, except: :destroy
    resources :categories, except: :destroy
    resources :measurements, except: :destroy
    resources :material_assets, except: :destroy do
      scope module: "material_assets" do
        resources :vendors, except: :show
      end
    end
    resources :groups, except: :destroy do
      post :copy, to: "groups#copy", on: :member
      scope module: "groups" do
        resources :ingredients, except: :show
        resources :semi_ingredients, except: :show
        resources :standards, except: :show
        resources :journals, except: :show
        resources :operations, except: :show
        resources :fields, except: :show
      end
    end
    resources :products, except: :destroy do
      scope module: "products" do
        resources :prices, except: :show
        resources :custom_prices, except: :show
        resources :box_packagings, except: :show
        resources :single_packagings, except: :show
      end
    end
    resources :semi_products, except: :destroy
    resources :clients, except: :destroy do
      scope module: "clients" do
        resources :sales_points, except: :show
      end
    end
    resources :packing_machines, except: :destroy do
      scope module: "packing_machines" do
        resources :containers, except: :show
      end
    end
    resources :promotions do
      scope module: "promotions" do
        resources :participants, except: :show
        resources :discounted_products, except: :show
      end
    end
    resources :activity_types
    resources :financial_categories
    resources :companies
    resources :bank_accounts
    resources :articles
  end

  scope module: "logistics" do
    resources :shipments do
      scope module: "shipments" do
        resources :route_sheets do
          scope module: "route_sheets" do
            resources :tracking_products
            resources :tracking_orders
          end
        end
      end
    end
    resources :returns do
      scope module: "returns" do
        resources :returned_products, except: :show
      end
    end
  end

  scope module: "mobile" do
    resource :feed, only: :show
    resources :scans, only: %i[ index new ]
    namespace :waybills do
      resources :arrivals, except: :index
      resources :write_offs, except: :index
      resources :transfers, except: :index
      resources :departures, except: :index
      resources :locations, only: %i[ new create ]

      scope ":waybill_id/mobile" do
        resources :qr_scans, except: %i[ new show ]
        resource :recommendation, only: :show
      end
    end
    namespace :journals do
      resources :outgoings, only: :index
      resources :incomings, only: :index
    end
    namespace :load do
      resources :assemblies do
        scope module: "assemblies" do
          resources :qr_scans, except: %i[ new show ]
          resource :recommendation, only: :show
        end
      end
    end
    namespace :tasks do
      resources :returns, except: %i[ new create destroy ]
    end
  end

  scope module: "finance" do
    resources :transactions do
      collection do
        get "search", to: "transactions#search"
      end
    end
    resources :account_transfers, only: %i[ new create ]
    resource :cash_flow, only: %i[ show create ]
  end

  namespace :reports do
    resource :export, only: :create
    resource :sales_channel, only: %i[ show create ]
    resource :client, only: %i[ show create ]
    resource :sales_point, only: %i[ show create ]
    resource :order, only: %i[ show create ]
    resource :return, only: %i[ show create ]
    resource :pivot, only: %i[ show create ]
    resource :arrival, only: %i[ show create ]
    resource :transfer, only: %i[ show create ]
    resource :write_off, only: %i[ show create ]
    resource :product_leftover, only: %i[ show create ]
    resource :material_asset_leftover, only: %i[ show create ]
  end

  get "/configurations/android", to: "configurations#android", as: :android_configuration
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/procurements/supply_material_assets/storages_controller.rb
module Procurements
  class SupplyMaterialAssets::StoragesController < ApplicationController
    include SupplyMaterialAssetScoped

    def index
      @storages = base_scope
    end

    private
      def base_scope
        @material_asset.storages.uniq
      end
  end
end

app/controllers/warehouse/storages/maps_controller.rb
module Warehouse
  class Storages::MapsController < ApplicationController
    include StorageScoped

    def show
      @zones = @storage.zones.ordered
    end
  end
end

app/controllers/warehouse/storages/subjects_controller.rb
module Warehouse
  class Storages::SubjectsController < ApplicationController
    include StorageScoped

    def index
      @subjects = base_scope
    end

    private
      def base_scope
        (@storage.for_assets? ? (@storage.material_assets + @storage.semi_products) : @storage.products).uniq
      end
  end
end

app/controllers/warehouse/storages/warehousers_controller.rb
module Warehouse
  class Storages::WarehousersController < ApplicationController
    include StorageScoped, ReadModes

    before_action :set_warehouser, only: %i[ edit update destroy ]
    before_action :set_read_mode, only: :index

    def index
      @pagy, @warehousers = pagy get_scope(params)
    end

    def new
      @warehouser = base_scope.new
    end

    def edit
    end

    def create
      @warehouser = base_scope.new(warehouser_params)

      if @warehouser.save
        redirect_on_create edit_storage_url(@storage)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @warehouser.update(warehouser_params)
        redirect_on_update edit_storage_url(@storage)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @warehouser.deactivate

      redirect_on_destroy edit_storage_url(@storage), text: t("actions.record_deactivated")
    end

    def search
      @warehousers = base_scope
    end

    private
      def base_scope
        @storage.warehousers.recent_first
      end

      def set_warehouser
        @warehouser = base_scope.find(params.expect(:id))
      end

      def warehouser_params
        params.expect(warehouser: %i[ user_id active duty replaceable_id ])
      end
  end
end

app/controllers/warehouse/storages/waybills_controller.rb
module Warehouse
  class Storages::WaybillsController < ApplicationController
    include StorageScoped

    def index
      @pagy, @waybills = pagy get_scope(params)
    end

    private
      def base_scope
        Waybill.filter_by_both_storage(@storage).recent_first
      end
  end
end

app/controllers/warehouse/storages/zones/lines/stacks/tiers_controller.rb
module Warehouse::Storages::Zones::Lines
  class Stacks::TiersController < ApplicationController
    include StorageScoped, ZoneScoped, LineScoped, StackScoped

    before_action :set_tier, only: %i[ show edit update destroy ]

    def index
      @pagy, @tiers = pagy get_scope(params)
    end

    def show
    end

    def new
      @tier = Tier.new
    end

    def edit
    end

    def create
      if Tier.repeat tier_params[:repeat], @stack
        redirect_on_create edit_storage_zone_line_stack_url(@storage, @zone, @line, @stack)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @tier.update(tier_params)
        redirect_on_update edit_storage_zone_line_stack_url(@storage, @zone, @line, @stack)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @tier.deactivate

      redirect_on_destroy storage_zone_line_stack_tiers_url(@storage, @zone, @line, @stack), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @stack.tiers.ordered
      end

      def set_tier
        @tier = base_scope.find(params.expect(:id))
      end

      def tier_params
        params.expect(tier: %i[ active repeat ])
      end
  end
end

app/controllers/warehouse/storages/zones/lines/stacks_controller.rb
module Warehouse::Storages::Zones
  class Lines::StacksController < ApplicationController
    include StorageScoped, ZoneScoped, LineScoped

    before_action :set_stack, only: %i[ show edit update destroy ]

    def index
      @pagy, @stacks = pagy get_scope(params)
    end

    def show
    end

    def new
      @stack = Stack.new
    end

    def edit
    end

    def create
      if Stack.repeat stack_params[:repeat], @line
        redirect_on_create edit_storage_zone_line_url(@storage, @zone, @line)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @stack.update(stack_params)
        redirect_on_update edit_storage_zone_line_url(@storage, @zone, @line)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @stack.deactivate

      redirect_on_destroy storage_zone_line_stacks_url(@storage, @zone, @line), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @line.stacks.ordered
      end

      def set_stack
        @stack = base_scope.find(params.expect(:id))
      end

      def stack_params
        params.expect(stack: %i[ active repeat ])
      end
  end
end

app/controllers/warehouse/storages/zones/lines_controller.rb
module Warehouse::Storages
  class Zones::LinesController < ApplicationController
    include StorageScoped, ZoneScoped

    before_action :set_line, only: %i[ show edit update destroy ]

    def index
      @pagy, @lines = pagy get_scope(params)
    end

    def show
    end

    def new
      @line = Line.new
    end

    def edit
    end

    def create
      if Line.repeat line_params[:repeat], @zone
        redirect_on_create edit_storage_zone_url(@storage, @zone)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @line.update(line_params)
        redirect_on_update edit_storage_zone_url(@storage, @zone)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @line.deactivate

      redirect_on_destroy storage_zone_lines_url(@storage, @zone), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @zone.lines.ordered
      end

      def set_line
        @line = base_scope.find(params.expect(:id))
      end

      def line_params
        params.expect(line: %i[ repeat active ])
      end
  end
end

app/controllers/warehouse/storages/zones_controller.rb
module Warehouse
  class Storages::ZonesController < ApplicationController
    include StorageScoped

    before_action :set_zone, only: %i[ show edit update destroy ]

    def index
      @pagy, @zones = pagy get_scope(params)
    end

    def show
    end

    def new
      @zone = Zone.new
    end

    def edit
    end

    def create
      @zone = Zone.new(zone_params)
      @zone.index_position = @storage.zones.count

      if @zone.save && @zone.locate_to(@storage)
        redirect_on_create edit_storage_url(@storage)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @zone.update(zone_params)
        redirect_on_update edit_storage_url(@storage)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @zone.deactivate

      redirect_on_destroy storage_zones_url(@storage), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @storage.zones.ordered
      end

      def set_zone
        @zone = base_scope.find(params.expect(:id))
      end

      def zone_params
        params.expect(zone: %i[ kind active ])
      end
  end
end

app/views/warehouse/storages/warehousers/_form.html.erb
<div class="flex flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <%= render "layouts/error_messages", resource: warehouser %>
    <%= form_with model: [@storage, warehouser], class: "space-y-4", data: { controller: "warehouser", warehouser_duty_value: warehouser.duty } do |form| %>
      <div>
        <%= form.label :user_id, class: "form-label" %>
        <%= form.select :user_id, options_from_collection_for_select(User.active.filter_by_role(%i[ admin procurement_officers warehouser ]), :id, :name, warehouser.user_id), { include_blank: true }, { disabled: !warehouser.active?, required: true, class: "form-select" } %>
      </div>

      <div>
        <%= form.label :duty, class: "form-label" %>
        <%= form.select :duty, options_for_enum_select(Warehouser, :duty, warehouser.duty), { include_blank: true }, { disabled: !warehouser.active?, required: true, data: { action: "warehouser#showReplaceables" }, class: "form-select" } %>
      </div>

      <div class="hidden" data-warehouser-target="selector">
        <%= form.label :replaceable_id, class: "form-label" %>
        <%= form.select :replaceable_id, options_from_collection_for_select(User.active.filter_by_role(%i[ admin procurement_officers warehouser ]), :id, :name, warehouser.replaceable_id), { include_blank: true }, { disabled: !warehouser.active?, required: false, class: "form-select" } %>
      </div>

      <% unless warehouser.new_record? || warehouser.active? %>
        <div class="relative flex gap-x-3">
          <div class="flex h-6 items-center">
            <%= form.check_box :active, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
          </div>
          <div class="text-sm leading-6">
            <%= form.label :active, class: "font-medium text-gray-900" %>
            <p class="text-gray-500"><%= t("forms.inactive_field") %></p>
          </div>
        </div>
      <% end %>

      <%= form.submit t("actions.save_record"), class: "btn" %>
    <% end %>
  </div>
</div>

app/views/warehouse/storages/warehousers/_warehouser.html.erb
<%= tag.div id: dom_id(warehouser), class: "table-row hover:bg-gray-50" do %>
  <div class="table-cell whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
    <span class="font-medium text-gray-900 <%= "line-through" unless warehouser.active? %>"><%= warehouser.user.name %></span>
  </div>
  <div class="table-cell px-3 py-3.5 text-left text-sm text-gray-900">
    <%= warehouser.user.email_address %>
  </div>
  <div class="table-cell px-3 py-3.5 text-left text-sm text-gray-900">
    <%= Warehouser.enum_to_s(:duty, warehouser.duty) %>
  </div>
  <% unless @readonly %>
    <div class="table-cell relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
      <div class="flex justify-end space-x-2">
        <%= link_to t("actions.edit_record"), edit_storage_warehouser_path(@storage, warehouser), data: { turbo_frame: "_top" }, class: "edit_warehouser text-indigo-600 hover:text-indigo-900" %>
        <% if warehouser.active? %>
          <%= link_to t("actions.destroy_record"), storage_warehouser_path(@storage, warehouser), data: { turbo_frame: "_top", turbo_method: :delete, turbo_confirm: t("actions.confirm") }, class: "destroy_warehouser text-red-600 hover:text-red-500" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/warehouse/storages/warehousers/edit.html.erb
<% content_for(:title) { @warehouser.user.name } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: storages_path, title: t("pages.storages")),
      NavLink.new(path: edit_storage_path(@storage), title: @storage.name),
      NavLink.new(path: edit_storage_warehouser_path(@storage, @warehouser), title: @warehouser.user.name)
    ]
  } %>
<% end %>

<%= render "form", warehouser: @warehouser %>

app/views/warehouse/storages/warehousers/index.html.erb
<%= turbo_frame_tag dom_id(@storage, :warehousers) do %>
  <% unless @readonly %>
    <div class="mb-4 sm:flex sm:items-center">
      <div class="sm:flex-none">
        <%= link_to new_storage_warehouser_path(@storage), data: { turbo_frame: "_top" }, class: "new_warehouser btn-create" do %>
          <%= inline_svg_tag "plus.svg", class: "h-5 w-5" %>
          <%= t("actions.create_record") %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="flow-root">
    <div class="-mx-2 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle px-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg">
          <div class="table min-w-full divide-y divide-gray-300">
            <div class="table-header-group bg-gray-50">
              <div class="table-row">
                <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                  <%= t("tables.cols.name") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= t("tables.cols.email_address") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= Warehouser.human_attribute_name(:duty) %>
                </div>
                <% unless @readonly %>
                  <div class="relative py-3.5 pl-3 pr-4 sm:pr-6"></div>
                <% end %>
              </div>
            </div>
            <div class="table-row-group divide-y divide-gray-200 bg-white">
              <%= render @warehousers %>
            </div>
          </div>
          <div class="px-2">
            <%== pagy_nav(@pagy) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/warehouse/storages/warehousers/new.html.erb
<% content_for(:title) { t("pages.warehousers") } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: storages_path, title: t("pages.storages")),
      NavLink.new(path: edit_storage_path(@storage), title: @storage.name),
      NavLink.new(path: new_storage_warehouser_path(@storage), title: t("pages.warehousers"))
    ]
  } %>
<% end %>

<%= render "form", warehouser: @warehouser %>

app/views/warehouse/storages/warehousers/search.turbo_stream.erb
<%= turbo_stream.update "waybill_receiver_id" do %>
  <option value=""></option>
  <%= options_from_collection_for_select(@warehousers, :user_id, :user_name) %>
<% end %>