config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "registrations#new", as: :join
  post "join/:join_code", to: "registrations#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  scope module: "sales" do
    scope "sales_channels/:sales_channel_id", as: "sales_channel", constraints: { sales_channel_id: /\d+/ } do
      resources :orders do
        scope module: "orders" do
          resources :positions, except: :show
        end
      end
    end

    resources :plans, except: %i[ new create ] do
      scope module: "plans" do
        resources :consolidations, except: %i[ show new create ]
        resources :groups, only: :index
      end
    end

    resources :sales_plans
  end

  namespace "production" do
    resources :plans, except: :destroy do
      scope module: "plans" do
        get :summary, to: "summaries#index"
        resources :units, controller: "production_units", except: %i[ new create destroy ] do
          scope module: "production_units" do
            resources :batches, except: :destroy do
              get "info", to: "batches#info", on: :member
              get "summary", to: "batches#summary", on: :member

              scope module: "batches" do
                resources :journals, only: :show
                resources :steps, only: %i[ edit create update ]
                resource :packing, except: :destroy do
                  scope module: "packings" do
                    resources :packaged_products, only: %i[ index edit update ] do
                      scope module: "packaged_products" do
                        resources :machineries, except: :show do
                          collection do
                            get "search", to: "machineries#search"
                          end
                        end
                      end
                    end
                  end
                end
                resource :cooking, except: :destroy do
                  scope module: "cookings" do
                    resources :cooked_semi_products, only: %i[ index edit update ]
                  end
                end
                resource :distribution, except: :destroy do
                  scope module: "distributions" do
                    resources :distributed_products, only: %i[ index edit update ] do
                      scope module: "distributed_products" do
                        resource :generation, only: %i[ show new create ] do
                          scope module: "generations" do
                            resources :boxes, only: :index do
                              collection do
                                post :download, to: "boxes#download"
                              end
                            end
                            resources :pallets, only: %i[ index new create ] do
                              collection do
                                post :download, to: "pallets#download"
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end

  scope module: "procurements" do
    resources :supply_orders, except: :destroy do
      collection do
        get "search", to: "supply_orders#search"
      end
    end
    resources :supply_operations do
      scope module: "supply_operations" do
        resources :leftovers, except: :show
      end
    end
    resources :supply_material_assets, only: %i[ index show ] do
      scope module: "supply_material_assets" do
        resources :storages, only: :index
      end
    end
  end

  scope module: "warehouse" do
    scope module: "storages" do
      get "warehousers/search", to: "warehousers#search", as: :warehousers_search
    end

    resources :storages, except: :destroy do
      scope module: "storages" do
        resources :subjects, only: :index
        resources :waybills, only: :index
        resources :zones do
          scope module: "zones" do
            resources :lines do
              scope module: "lines" do
                resources :stacks do
                  scope module: "stacks" do
                    resources :tiers
                  end
                end
              end
            end
          end
        end
        resource :map, only: :show
        resources :warehousers, except: :show
      end
    end
    resources :waybills, only: %i[ index show edit update ] do
      scope module: "waybills" do
        resources :leftovers, only: :index
        resources :qr_scans, only: %i[ index edit update ]
      end
    end
    resources :boxes, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "boxes#location", as: :location
      end
    end
    resources :pallets, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "pallets#location", as: :location
      end
    end
  end

  scope module: "settings" do
    resources :regions, except: :destroy
    resources :sales_channels, except: :destroy
    resources :suppliers, except: :destroy
    resources :categories, except: :destroy
    resources :measurements, except: :destroy
    resources :material_assets, except: :destroy do
      scope module: "material_assets" do
        resources :vendors, except: :show
      end
    end
    resources :groups, except: :destroy do
      post :copy, to: "groups#copy", on: :member
      scope module: "groups" do
        resources :ingredients, except: :show
        resources :semi_ingredients, except: :show
        resources :standards, except: :show
        resources :journals, except: :show
        resources :operations, except: :show
        resources :fields, except: :show
      end
    end
    resources :products, except: :destroy do
      scope module: "products" do
        resources :prices, except: :show
        resources :custom_prices, except: :show
        resources :box_packagings, except: :show
        resources :single_packagings, except: :show
      end
    end
    resources :semi_products, except: :destroy
    resources :clients, except: :destroy do
      scope module: "clients" do
        resources :sales_points, except: :show
      end
    end
    resources :packing_machines, except: :destroy do
      scope module: "packing_machines" do
        resources :containers, except: :show
      end
    end
    resources :promotions do
      scope module: "promotions" do
        resources :participants, except: :show
        resources :discounted_products, except: :show
      end
    end
    resources :activity_types
    resources :financial_categories
    resources :companies
    resources :bank_accounts
    resources :articles
  end

  scope module: "logistics" do
    resources :shipments do
      scope module: "shipments" do
        resources :route_sheets do
          scope module: "route_sheets" do
            resources :tracking_products
            resources :tracking_orders
          end
        end
      end
    end
    resources :returns do
      scope module: "returns" do
        resources :returned_products, except: :show
      end
    end
  end

  scope module: "mobile" do
    resource :feed, only: :show
    resources :scans, only: %i[ index new ]
    namespace :waybills do
      resources :arrivals, except: :index
      resources :write_offs, except: :index
      resources :transfers, except: :index
      resources :departures, except: :index
      resources :locations, only: %i[ new create ]

      scope ":waybill_id/mobile" do
        resources :qr_scans, except: %i[ new show ]
        resource :recommendation, only: :show
      end
    end
    namespace :journals do
      resources :outgoings, only: :index
      resources :incomings, only: :index
    end
    namespace :load do
      resources :assemblies do
        scope module: "assemblies" do
          resources :qr_scans, except: %i[ new show ]
          resource :recommendation, only: :show
        end
      end
    end
    namespace :tasks do
      resources :returns, except: %i[ new create destroy ]
    end
  end

  scope module: "finance" do
    resources :transactions do
      collection do
        get "search", to: "transactions#search"
      end
    end
    resources :account_transfers, only: %i[ new create ]
    resource :cash_flow, only: %i[ show create ]
  end

  namespace :reports do
    resource :export, only: :create
    resource :sales_channel, only: %i[ show create ]
    resource :client, only: %i[ show create ]
    resource :sales_point, only: %i[ show create ]
    resource :order, only: %i[ show create ]
    resource :return, only: %i[ show create ]
    resource :pivot, only: %i[ show create ]
    resource :arrival, only: %i[ show create ]
    resource :transfer, only: %i[ show create ]
    resource :write_off, only: %i[ show create ]
    resource :product_leftover, only: %i[ show create ]
    resource :material_asset_leftover, only: %i[ show create ]
  end

  get "/configurations/android", to: "configurations#android", as: :android_configuration
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/line.rb
class Line < ApplicationRecord
  include Deactivatable, Codable, Markable, Locatable, Repeatable, QrGeneratable

  has_many :zones, through: :locations, source: :positionable, source_type: "Zone"
  has_many :stacks, through: :elements, source: :storable, source_type: "Stack"

  has_many :tiers, through: :stacks
  has_many :pallets_in_tiers, through: :tiers, source: :pallets
  has_many :boxes_in_tiers, through: :tiers, source: :boxes
  has_many :boxes_in_tiers_in_pallets, through: :tiers, source: :boxes_in_pallets

  def counter_base
    self.stacks.count
  end

  private
    def generate_code
      parts = [ "L", SecureRandom.hex(8) ]
      parts.join("-").upcase
    end

    def pallet_scopes
      [ pallets_in_tiers ]
    end

    def box_scopes
      [ boxes_in_tiers, boxes_in_tiers_in_pallets ]
    end

    def hierarchy_classes
      %w[ Zone ]
    end
end

app/models/zone.rb
class Zone < ApplicationRecord
  include Deactivatable, Codable, Markable, Locatable, QrGeneratable

  enum :kind, %w[ arrival hold ship ].index_by(&:itself), default: :hold

  has_many :storages, through: :locations, source: :positionable, source_type: "Storage"

  # Прямые адреса
  has_many :lines, through: :elements, source: :storable, source_type: "Line"
  has_many :pallets, through: :elements, source: :storable, source_type: "Pallet"
  has_many :boxes, through: :elements, source: :storable, source_type: "Box"
  has_many :boxes_in_pallets, through: :pallets, source: :boxes

  # Сквозные адреса
  has_many :stacks, through: :lines
  has_many :tiers, through: :stacks
  has_many :pallets_in_tiers, through: :tiers, source: :pallets
  has_many :boxes_in_tiers, through: :tiers, source: :boxes
  has_many :boxes_in_tiers_in_pallets, through: :tiers, source: :boxes_in_pallets

  has_many :child_qr_scans, as: :sourceable, class_name: "QrScan", dependent: :destroy

  has_many :assemblies, dependent: :destroy

  scope :filter_by_kind, ->(kind) { where(kind: kind) }

  scope :for_mobile, ->() { filter_by_kind(:ship) }

  def counter_base
    self.lines.count
  end

  private
    def generate_code
      parts = [ "Z", SecureRandom.hex(8) ]
      parts.join("-").upcase
    end

    def pallet_scopes
      [ pallets, pallets_in_tiers ]
    end

    def box_scopes
      [ boxes, boxes_in_pallets, boxes_in_tiers, boxes_in_tiers_in_pallets ]
    end

    def hierarchy_classes
      %w[ Storage ]
    end
end

app/controllers/warehouse/storages/zones/lines/stacks/tiers_controller.rb
module Warehouse::Storages::Zones::Lines
  class Stacks::TiersController < ApplicationController
    include StorageScoped, ZoneScoped, LineScoped, StackScoped

    before_action :set_tier, only: %i[ show edit update destroy ]

    def index
      @pagy, @tiers = pagy get_scope(params)
    end

    def show
    end

    def new
      @tier = Tier.new
    end

    def edit
    end

    def create
      if Tier.repeat tier_params[:repeat], @stack
        redirect_on_create edit_storage_zone_line_stack_url(@storage, @zone, @line, @stack)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @tier.update(tier_params)
        redirect_on_update edit_storage_zone_line_stack_url(@storage, @zone, @line, @stack)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @tier.deactivate

      redirect_on_destroy storage_zone_line_stack_tiers_url(@storage, @zone, @line, @stack), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @stack.tiers.ordered
      end

      def set_tier
        @tier = base_scope.find(params.expect(:id))
      end

      def tier_params
        params.expect(tier: %i[ active repeat ])
      end
  end
end

app/controllers/warehouse/storages/zones/lines/stacks_controller.rb
module Warehouse::Storages::Zones
  class Lines::StacksController < ApplicationController
    include StorageScoped, ZoneScoped, LineScoped

    before_action :set_stack, only: %i[ show edit update destroy ]

    def index
      @pagy, @stacks = pagy get_scope(params)
    end

    def show
    end

    def new
      @stack = Stack.new
    end

    def edit
    end

    def create
      if Stack.repeat stack_params[:repeat], @line
        redirect_on_create edit_storage_zone_line_url(@storage, @zone, @line)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @stack.update(stack_params)
        redirect_on_update edit_storage_zone_line_url(@storage, @zone, @line)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @stack.deactivate

      redirect_on_destroy storage_zone_line_stacks_url(@storage, @zone, @line), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @line.stacks.ordered
      end

      def set_stack
        @stack = base_scope.find(params.expect(:id))
      end

      def stack_params
        params.expect(stack: %i[ active repeat ])
      end
  end
end

app/controllers/warehouse/storages/zones/lines_controller.rb
module Warehouse::Storages
  class Zones::LinesController < ApplicationController
    include StorageScoped, ZoneScoped

    before_action :set_line, only: %i[ show edit update destroy ]

    def index
      @pagy, @lines = pagy get_scope(params)
    end

    def show
    end

    def new
      @line = Line.new
    end

    def edit
    end

    def create
      if Line.repeat line_params[:repeat], @zone
        redirect_on_create edit_storage_zone_url(@storage, @zone)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @line.update(line_params)
        redirect_on_update edit_storage_zone_url(@storage, @zone)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @line.deactivate

      redirect_on_destroy storage_zone_lines_url(@storage, @zone), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @zone.lines.ordered
      end

      def set_line
        @line = base_scope.find(params.expect(:id))
      end

      def line_params
        params.expect(line: %i[ repeat active ])
      end
  end
end

app/controllers/warehouse/storages/zones_controller.rb
module Warehouse
  class Storages::ZonesController < ApplicationController
    include StorageScoped

    before_action :set_zone, only: %i[ show edit update destroy ]

    def index
      @pagy, @zones = pagy get_scope(params)
    end

    def show
    end

    def new
      @zone = Zone.new
    end

    def edit
    end

    def create
      @zone = Zone.new(zone_params)
      @zone.index_position = @storage.zones.count

      if @zone.save && @zone.locate_to(@storage)
        redirect_on_create edit_storage_url(@storage)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @zone.update(zone_params)
        redirect_on_update edit_storage_url(@storage)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @zone.deactivate

      redirect_on_destroy storage_zones_url(@storage), text: t("actions.record_deactivated")
    end

    private
      def base_scope
        @storage.zones.ordered
      end

      def set_zone
        @zone = base_scope.find(params.expect(:id))
      end

      def zone_params
        params.expect(zone: %i[ kind active ])
      end
  end
end

app/views/warehouse/storages/zones/lines/_form.html.erb
<div class="flex flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full">
    <%= render "layouts/error_messages", resource: line %>
    <%= form_with model: [@storage, @zone, line], class: "space-y-12" do |form| %>
      <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
        <div>
          <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.main_info") %></h2>
        </div>
        <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
          <%= fields_for @zone do |zone_form| %>
            <div class="sm:col-span-4">
              <%= zone_form.label :code, class: "form-label" %>
              <%= zone_form.text_field :code, readonly: true, class: "mt-2 form-input" %>
            </div>
          <% end %>

          <% if line.new_record? %>
            <div class="sm:col-span-4">
              <%= form.label :repeat, class: "form-label" %>
              <%= form.number_field :repeat, autocomplete: "repeat", autofocus: true, required: true, class: "mt-2 form-input" %>
            </div>
          <% else %>
            <div class="sm:col-span-4">
              <%= form.label :code, class: "form-label" %>
              <%= form.text_field :code, readonly: true, class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :display_index, class: "form-label" %>
              <%= form.text_field :display_index, readonly: true, class: "mt-2 form-input" %>
            </div>
          <% end %>

          <% if line.active? %>
            <%= form.hidden_field :active %>
          <% else %>
            <div class="sm:col-span-4 relative flex gap-x-3">
              <div class="flex h-6 items-center">
                <%= form.check_box :active, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
              </div>
              <div class="text-sm leading-6">
                <%= form.label :active, class: "font-medium text-gray-900" %>
                <p class="text-gray-500"><%= t("forms.inactive_promo") %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
        <div>
          <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.stacks") %></h2>
        </div>
        <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
          <% if line.new_record? %>
            <div class="sm:col-span-4">
              <p class="mt-1 text-sm leading-6 text-gray-600"><%= t("forms.save_parent_record") %></p>
            </div>
          <% else %>
            <div class="sm:col-span-full">
              <%= turbo_frame_tag dom_id(line, :stacks), src: storage_zone_line_stacks_path(@storage, @zone, line) do %>
                <%= inline_svg_tag "spinner.svg" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="mt-6 flex items-center justify-end gap-x-6">
        <%= form.submit t("actions.save_record"), class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    <% end %>
  </div>
</div>

app/views/warehouse/storages/zones/lines/_line.html.erb
<%= tag.div id: dom_id(line), class: "table-row hover:bg-gray-50" do %>
  <div class="table-cell whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 <%= "line-through text-red-500" unless line.active? %>">
    <%= link_to line.code, storage_zone_line_path(@storage, @zone, line), class: "text-indigo-600", data: { turbo_frame: "_top" } %>
  </div>
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500">
    <%= line.display_index %>
  </div>
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500">
    <%= number_with_delimiter line.stacks.count %>
  </div>
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500">
    <%= number_with_delimiter line.all_pallets.count %>
  </div>
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500">
    <%= number_with_delimiter line.all_boxes.count %>
  </div>
  <div class="table-cell relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
    <div class="flex justify-end space-x-2">
      <%= link_to t("actions.edit_record"), edit_storage_zone_line_path(@storage, @zone, line), data: { turbo_frame: "_top" }, class: "edit_line text-indigo-600 hover:text-indigo-900" %>
      <% if line.can_be_deactivated? && line.active? %>
        <%= button_to t("actions.destroy_record"), storage_zone_line_path(@storage, @zone, line), method: :delete, form: { data: { turbo_confirm: t("actions.confirm") }, class: "destroy_line text-red-600 hover:text-red-500" } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/warehouse/storages/zones/lines/edit.html.erb
<% content_for(:title) { t("pages.line", index: @line.display_index) } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: storages_path, title: t("pages.storages")),
      NavLink.new(path: edit_storage_path(@storage), title: @storage.name),
      NavLink.new(path: edit_storage_zone_path(@storage, @zone), title: t("pages.zone", index: @zone.display_index)),
      NavLink.new(path: edit_storage_zone_line_path(@storage, @zone, @line), title: t("pages.line", index: @line.display_index)),
    ]
  } %>
<% end %>

<%= render "form", line: @line %>

app/views/warehouse/storages/zones/lines/index.html.erb
<%= turbo_frame_tag dom_id(@zone, :lines) do %>
  <div class="mb-4 sm:flex sm:items-center">
    <div class="sm:flex-none">
      <%= link_to new_storage_zone_line_path(@storage, @zone), data: { turbo_frame: "_top" }, class: "new_line btn-create" do %>
        <%= inline_svg_tag "plus.svg", class: "h-5 w-5" %>
        <%= t("actions.create_record") %>
      <% end %>
    </div>
  </div>
  <div class="flow-root">
    <div class="-mx-2 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle px-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg">
          <div class="table min-w-full divide-y divide-gray-300">
            <div class="table-header-group bg-gray-50">
              <div class="table-row">
                <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                  <%= t("tables.cols.code") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= t("tables.cols.number") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= t("tables.cols.stacks") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= t("tables.cols.pallets") %>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <%= t("tables.cols.boxes") %>
                </div>
                <div class="relative py-3.5 pl-3 pr-4 sm:pr-6"></div>
              </div>
            </div>
            <div class="table-row-group divide-y divide-gray-200 bg-white">
              <%= render @lines %>
            </div>
          </div>
          <div class="px-2">
            <%== pagy_nav(@pagy) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/warehouse/storages/zones/lines/new.html.erb
<% content_for(:title) { t("pages.lines") } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: storages_path, title: t("pages.storages")),
      NavLink.new(path: edit_storage_path(@storage), title: @storage.name),
      NavLink.new(path: edit_storage_zone_path(@storage, @zone), title: t("pages.zone", index: @zone.display_index)),
      NavLink.new(path: new_storage_zone_line_path(@storage, @zone), title: t("pages.lines"))
    ]
  } %>
<% end %>

<%= render "form", line: @line %>

app/views/warehouse/storages/zones/lines/show.html.erb
<% content_for(:title) { t("pages.line", index: @line.display_index) } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: storages_path, title: t("pages.storages")),
      NavLink.new(path: storage_path(@storage), title: @storage.name),
      NavLink.new(path: storage_zone_path(@storage, @zone), title: t("pages.zone", index: @zone.display_index)),
      NavLink.new(path: storage_zone_line_path(@storage, @zone, @line), title: t("pages.line", index: @line.display_index)),
    ]
  } %>
<% end %>

<div class="flex flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full">
    <%= fields_for @line do |form| %>
      <div>
        <div class="space-y-12">
          <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
            <div>
              <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.main_info") %></h2>
            </div>
            <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
              <div class="sm:col-span-4">
                <%= form.label :code, class: "form-label" %>
                <div class="flex items-end space-x-2">
                  <%= form.text_field :code, disabled: true, class: "mt-2 form-input" %>
                  <%= render "shared/qr_dialog", qr_text: @line.code %>
                  <% if @line.qr_image.attached? %>
                    <%= link_to rails_blob_path(@line.qr_image, disposition: "attachment"), class: "icon-btn" do %>
                      <%= inline_svg_tag "download.svg", class: "size-6" %>
                    <% end %>
                  <% end %>
                </div>
              </div>

              <div class="sm:col-span-4">
                <%= form.label :display_index, class: "form-label" %>
                <%= form.text_field :display_index, readonly: true, class: "mt-2 form-input" %>
              </div>
            </div>
          </div>
          <% position = @line.current_position %>
          <% if position %>
            <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
              <div>
                <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.location") %></h2>
              </div>
              <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
                <%= fields_for position do |pos_form| %>
                  <div class="sm:col-span-4">
                    <%= pos_form.label :code, class: "form-label" %>
                    <div class="flex items-end space-x-2">
                      <%= pos_form.text_field :code, disabled: true, class: "mt-2 form-input" %>
                      <%= render "shared/qr_dialog", qr_text: position.code %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
            <div>
              <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.boxes") %></h2>
            </div>
            <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
              <div class="sm:col-span-full">
                <%= turbo_frame_tag :location_boxes, src: location_boxes_path(@line, @line.model_name.name) do %>
                  <%= inline_svg_tag "spinner.svg" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
            <div>
              <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.pallets") %></h2>
            </div>
            <div class="grid max-w-3xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-3">
              <div class="sm:col-span-full">
                <%= turbo_frame_tag :location_pallets, src: location_pallets_path(@line, @line.model_name.name) do %>
                  <%= inline_svg_tag "spinner.svg" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>