config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "registrations#new", as: :join
  post "join/:join_code", to: "registrations#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  scope module: "sales" do
    scope "sales_channels/:sales_channel_id", as: "sales_channel", constraints: { sales_channel_id: /\d+/ } do
      resources :orders do
        scope module: "orders" do
          resources :positions, except: :show
        end
      end
    end

    resources :plans, except: %i[ new create ] do
      scope module: "plans" do
        resources :consolidations, except: %i[ show new create ]
        resources :groups, only: :index
      end
    end

    resources :sales_plans
  end

  namespace "production" do
    resources :plans, except: :destroy do
      scope module: "plans" do
        get :summary, to: "summaries#index"
        resources :units, controller: "production_units", except: %i[ new create destroy ] do
          scope module: "production_units" do
            resources :batches, except: :destroy do
              get "info", to: "batches#info", on: :member
              get "summary", to: "batches#summary", on: :member

              scope module: "batches" do
                resources :journals, only: :show
                resources :steps, only: %i[ edit create update ]
                resource :packing, except: :destroy do
                  scope module: "packings" do
                    resources :packaged_products, only: %i[ index edit update ] do
                      scope module: "packaged_products" do
                        resources :machineries, except: :show do
                          collection do
                            get "search", to: "machineries#search"
                          end
                        end
                      end
                    end
                  end
                end
                resource :cooking, except: :destroy do
                  scope module: "cookings" do
                    resources :cooked_semi_products, only: %i[ index edit update ]
                  end
                end
                resource :distribution, except: :destroy do
                  scope module: "distributions" do
                    resources :distributed_products, only: %i[ index edit update ] do
                      scope module: "distributed_products" do
                        resource :generation, only: %i[ show new create ] do
                          scope module: "generations" do
                            resources :boxes, only: :index do
                              collection do
                                post :download, to: "boxes#download"
                              end
                            end
                            resources :pallets, only: %i[ index new create ] do
                              collection do
                                post :download, to: "pallets#download"
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end

  scope module: "procurements" do
    resources :supply_orders, except: :destroy do
      collection do
        get "search", to: "supply_orders#search"
      end
    end
    resources :supply_operations do
      scope module: "supply_operations" do
        resources :leftovers, except: :show
      end
    end
    resources :supply_material_assets, only: %i[ index show ] do
      scope module: "supply_material_assets" do
        resources :storages, only: :index
      end
    end
  end

  scope module: "warehouse" do
    scope module: "storages" do
      get "warehousers/search", to: "warehousers#search", as: :warehousers_search
    end

    resources :storages, except: :destroy do
      scope module: "storages" do
        resources :subjects, only: :index
        resources :waybills, only: :index
        resources :zones do
          scope module: "zones" do
            resources :lines do
              scope module: "lines" do
                resources :stacks do
                  scope module: "stacks" do
                    resources :tiers
                  end
                end
              end
            end
          end
        end
        resource :map, only: :show
        resources :warehousers, except: :show
      end
    end
    resources :waybills, only: %i[ index show edit update ] do
      scope module: "waybills" do
        resources :leftovers, only: :index
        resources :qr_scans, only: %i[ index edit update ]
      end
    end
    resources :boxes, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "boxes#location", as: :location
      end
    end
    resources :pallets, only: %i[ index show ] do
      collection do
        get "location/:positionable_id/:positionable_type", to: "pallets#location", as: :location
      end
    end
  end

  scope module: "settings" do
    resources :regions, except: :destroy
    resources :sales_channels, except: :destroy
    resources :suppliers, except: :destroy
    resources :categories, except: :destroy
    resources :measurements, except: :destroy
    resources :material_assets, except: :destroy do
      scope module: "material_assets" do
        resources :vendors, except: :show
      end
    end
    resources :groups, except: :destroy do
      post :copy, to: "groups#copy", on: :member
      scope module: "groups" do
        resources :ingredients, except: :show
        resources :semi_ingredients, except: :show
        resources :standards, except: :show
        resources :journals, except: :show
        resources :operations, except: :show
        resources :fields, except: :show
      end
    end
    resources :products, except: :destroy do
      scope module: "products" do
        resources :prices, except: :show
        resources :custom_prices, except: :show
        resources :box_packagings, except: :show
        resources :single_packagings, except: :show
      end
    end
    resources :semi_products, except: :destroy
    resources :clients, except: :destroy do
      scope module: "clients" do
        resources :sales_points, except: :show
      end
    end
    resources :packing_machines, except: :destroy do
      scope module: "packing_machines" do
        resources :containers, except: :show
      end
    end
    resources :promotions do
      scope module: "promotions" do
        resources :participants, except: :show
        resources :discounted_products, except: :show
      end
    end
    resources :activity_types
    resources :financial_categories
    resources :companies
    resources :bank_accounts
    resources :articles
  end

  scope module: "logistics" do
    resources :shipments do
      scope module: "shipments" do
        resources :route_sheets do
          scope module: "route_sheets" do
            resources :tracking_products
            resources :tracking_orders
          end
        end
      end
    end
    resources :returns do
      scope module: "returns" do
        resources :returned_products, except: :show
      end
    end
  end

  scope module: "mobile" do
    resource :feed, only: :show
    resources :scans, only: %i[ index new ]
    namespace :waybills do
      resources :arrivals, except: :index
      resources :write_offs, except: :index
      resources :transfers, except: :index
      resources :departures, except: :index
      resources :locations, only: %i[ new create ]

      scope ":waybill_id/mobile" do
        resources :qr_scans, except: %i[ new show ]
        resource :recommendation, only: :show
      end
    end
    namespace :journals do
      resources :outgoings, only: :index
      resources :incomings, only: :index
    end
    namespace :load do
      resources :assemblies do
        scope module: "assemblies" do
          resources :qr_scans, except: %i[ new show ]
          resource :recommendation, only: :show
        end
      end
    end
    namespace :tasks do
      resources :returns, except: %i[ new create destroy ]
    end
  end

  scope module: "finance" do
    resources :transactions do
      collection do
        get "search", to: "transactions#search"
      end
    end
    resources :account_transfers, only: %i[ new create ]
    resource :cash_flow, only: %i[ show create ]
  end

  namespace :reports do
    resource :export, only: :create
    resource :sales_channel, only: %i[ show create ]
    resource :client, only: %i[ show create ]
    resource :sales_point, only: %i[ show create ]
    resource :order, only: %i[ show create ]
    resource :return, only: %i[ show create ]
    resource :pivot, only: %i[ show create ]
    resource :arrival, only: %i[ show create ]
    resource :transfer, only: %i[ show create ]
    resource :write_off, only: %i[ show create ]
    resource :product_leftover, only: %i[ show create ]
    resource :material_asset_leftover, only: %i[ show create ]
  end

  get "/configurations/android", to: "configurations#android", as: :android_configuration
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include Entitable

  has_many :vendors, dependent: :destroy
  has_many :transactions, as: :contragent, dependent: :nullify

  validates_presence_of :identification_number, if: :foreign?
  validates_presence_of :bin, unless: :foreign?
  validates_uniqueness_of :bin, case_sensitive: false, allow_blank: true
  validates_length_of :bin, is: 12, allow_blank: true

  scope :filter_by_name_or_bin, ->(query) { where("LOWER(name) LIKE ? OR LOWER(bin) LIKE ? OR LOWER(identification_number) LIKE ?", like(query), like(query), like(query)) }
end

app/controllers/settings/activity_types_controller.rb
class Settings::ActivityTypesController < ApplicationController
  before_action :ensure_can_administer, only: %i[ create update destroy ]
  before_action :set_activity_type, only: %i[ show edit update destroy ]

  def index
    @pagy, @activity_types = pagy get_scope(params)
  end

  def show
  end

  def new
    @activity_type = base_scope.new
  end

  def edit
  end

  def create
    @activity_type = base_scope.new(activity_type_params)

    if @activity_type.save
      redirect_on_create activity_types_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @activity_type.update(activity_type_params)
      redirect_on_update activity_types_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity_type.destroy!

    redirect_on_destroy activity_types_url
  end

  private
    def base_scope
      ActivityType.recent_first
    end

    def search_methods
      []
    end

    def set_activity_type
      @activity_type = base_scope.find(params.expect(:id))
    end

    def activity_type_params
      params.expect(activity_type: %i[ name order_number ])
    end
end

app/controllers/settings/articles_controller.rb
class Settings::ArticlesController < ApplicationController
  before_action :ensure_can_administer, only: %i[ create update destroy ]
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_financial_categories, only: %i[ new create edit update ]

  def index
    @pagy, @articles = pagy get_scope(params)
  end

  def show
  end

  def new
    @article = base_scope.new(kind: @kind)
  end

  def edit
  end

  def create
    @article = base_scope.new(article_params)

    if @article.save
      redirect_on_create articles_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_on_update articles_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy!

    redirect_on_destroy articles_url
  end

  private
    def base_scope
      Article.recent_first
    end

    def search_methods
      []
    end

    def set_article
      @article = base_scope.find(params.expect(:id))
    end

    def article_params
      params.expect(article: %i[ financial_category_id activity_type_id name kind min_amount bypass_control system suppliable ])
    end

    def set_financial_categories
      @kind = @article.nil? ? params[:kind].presence || "income" : @article.kind
      @financial_categories = FinancialCategory.filter_by_kind(@kind)
    end
end

app/controllers/settings/bank_accounts_controller.rb
class Settings::BankAccountsController < ApplicationController
  before_action :ensure_can_administer, only: %i[ create update destroy ]
  before_action :set_bank_account, only: %i[ show edit update destroy ]

  def index
    @pagy, @bank_accounts = pagy get_scope(params)
  end

  def show
  end

  def new
    @bank_account = base_scope.new
  end

  def edit
  end

  def create
    @bank_account = base_scope.new(bank_account_params)

    if @bank_account.save
      redirect_on_create bank_accounts_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bank_account.update(bank_account_params)
      redirect_on_update bank_accounts_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bank_account.destroy!

    redirect_on_destroy bank_accounts_url
  end

  private
    def base_scope
      BankAccount.recent_first
    end

    def search_methods
      []
    end

    def set_bank_account
      @bank_account = base_scope.find(params.expect(:id))
    end

    def bank_account_params
      params.expect(bank_account: %i[ company_id name number main ])
    end
end

app/controllers/settings/categories_controller.rb
class Settings::CategoriesController < ApplicationController
  before_action :ensure_can_administer, only: %i[ create update ]
  before_action :set_category, only: %i[ show edit update ]

  def index
    @pagy, @categories = pagy get_scope(params)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_on_create categories_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_on_update categories_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def base_scope
      Category.recent_first
    end

    def search_methods
      []
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :kind)
    end
end

app/controllers/settings/clients/sales_points_controller.rb
module Settings
  class Clients::SalesPointsController < ApplicationController
    include ClientScoped, ReadModes

    before_action :ensure_can_administer, only: %i[ create update destroy ]
    before_action :set_sales_point, only: %i[ edit update destroy ]
    before_action :set_read_mode, only: :index

    def index
      @sales_points = base_scope.recent_first
    end

    def new
      @sales_point = base_scope.new
    end

    def edit
    end

    def create
      @sales_point = base_scope.new(sales_point_params)

      if @sales_point.save
        redirect_on_create edit_client_path(@client)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @sales_point.update(sales_point_params)
        redirect_on_update edit_client_path(@client)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @sales_point.deactivate

      redirect_on_destroy edit_client_path(@client)
    end

    private
      def base_scope
        @client.sales_points
      end

      def search_methods
        []
      end

      def set_sales_point
        @sales_point = base_scope.find(params[:id])
      end

      def sales_point_params
        params.require(:sales_point).permit(:region_id, :name, :address, :phone_number, :active)
      end
  end
end

app/controllers/settings/clients_controller.rb
class Settings::ClientsController < ApplicationController
  before_action :ensure_can_administer, only: %i[ create update ]
  before_action :set_client, only: %i[ show edit update ]

  def index
    @pagy, @clients = pagy get_scope(params)
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_on_create edit_client_url(@client)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @client.update(client_params)
      redirect_on_update clients_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def base_scope
      Client.recent_first
    end

    def search_methods
      [ :name_or_bin ]
    end

    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :bin, :contact_person, :job_title, :phone_number, :email_address, :entity_code, :bank_name, :bank_account, :bank_code, :manager_id, :fifo_in_days, uploads: [])
    end
end

app/views/settings/suppliers/_form.html.erb
<div class="flex flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full">
    <%= render "layouts/error_messages", resource: supplier %>
    <%= form_with model: supplier do |form| %>
      <div class="space-y-12">
        <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
          <div>
            <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.profile") %></h2>
            <p class="mt-1 text-sm leading-6 text-gray-600"><%= t("forms.profile_extra") %></p>
          </div>

          <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2" data-controller="supplier" data-supplier-foreign-value="<%= supplier.foreign? %>">
            <div class="sm:col-span-4">
              <%= form.label :manager_id, class: "form-label" %>
              <%= form.select :manager_id, options_from_collection_for_select(User.procurement_officers, :id, :name, supplier.manager_id), { include_blank: true, required: true }, { class: "mt-2 form-select" } %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, autocomplete: "name", autofocus: true, required: true, class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4 relative flex gap-x-3">
              <div class="flex h-6 items-center">
                <%= form.check_box :foreign, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600", data: { action: "supplier#toggle" } %>
              </div>
              <div class="text-sm leading-6">
                <%= form.label :foreign, class: "font-medium text-gray-900" %>
                <p class="text-gray-500"><%= t("forms.foreign_company") %></p>
              </div>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :bin, class: "form-label" %>
              <%= form.text_field :bin, autocomplete: "bin", required: true, class: "mt-2 form-input", max: 12, data: { supplier_target: "bin" } %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :identification_number, class: "form-label" %>
              <%= form.text_field :identification_number, autocomplete: "identification-number", required: true, class: "mt-2 form-input", data: { supplier_target: "number" } %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :contact_person, class: "form-label" %>
              <%= form.text_field :contact_person, autocomplete: "contact-person", class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :job_title, class: "form-label" %>
              <%= form.text_field :job_title, autocomplete: "job-title", class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :phone_number, class: "form-label" %>
              <%= form.phone_field :phone_number, autocomplete: "phone-number", class: "mt-2 form-input", pattern: '\+[0-9]+[0-9]{3}[0-9]{7}' %>
              <p class="mt-3 text-sm leading-6 text-gray-600"><%= t("forms.phone_number_hint") %></p>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :email_address, class: "form-label" %>
              <%= form.email_field :email_address, autocomplete: "email-address", class: "mt-2 form-input" %>
            </div>
          </div>
        </div>

        <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
          <div>
            <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.bank_details") %></h2>
            <p class="mt-1 text-sm leading-6 text-gray-600"><%= t("forms.bank_details_extra") %></p>
          </div>

          <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
            <div class="sm:col-span-4">
              <%= form.label :entity_code, class: "form-label" %>
              <%= form.text_field :entity_code, autocomplete: "entity-code", class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :bank_name, class: "form-label" %>
              <%= form.text_field :bank_name, autocomplete: "bank-name", class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :bank_account, class: "form-label" %>
              <%= form.text_field :bank_account, autocomplete: "bank-account", class: "mt-2 form-input" %>
            </div>

            <div class="sm:col-span-4">
              <%= form.label :bank_code, class: "form-label" %>
              <%= form.text_field :bank_code, autocomplete: "bank-code", class: "mt-2 form-input" %>
            </div>
          </div>
        </div>

        <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
          <div>
            <h2 class="text-base font-semibold leading-7 text-gray-900"><%= t("forms.documents") %></h2>
          </div>
          <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-4 sm:grid-cols-6 md:col-span-2">
            <% if supplier.new_record? %>
              <div class="sm:col-span-4">
                <p class="mt-1 text-sm leading-6 text-gray-600"><%= t("forms.save_parent_record") %></p>
              </div>
            <% else %>
              <div class="sm:col-span-4">
                <% supplier.uploads.each do |upload| %>
                  <%= form.hidden_field :uploads, multiple: true, value: upload.signed_id, id: "supplier_uploads_#{ upload.id }" %>
                <% end %>
                <%= form.file_field :uploads, multiple: true, class: "mt-2 form-input" %>
              </div>

              <% if supplier.uploads.attached? %>
                <%= render "uploads", supplier: supplier %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mt-6 flex items-center justify-end gap-x-6">
        <%= form.submit t("actions.save_record"), class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/suppliers/_search.html.erb
<div class="sm:flex-auto">
  <%= form_tag suppliers_path, data: {}, method: :get do %>
    <div class="flex rounded-md shadow-sm">
      <div class="relative flex flex-grow items-stretch focus-within:z-10">
        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
          <%= inline_svg_tag "search.svg", class: "h-5 w-5 text-gray-400" %>
        </div>
        <%= text_field :search, :name_or_bin, placeholder: t("actions.search_by_name_or_bin"), class: "block w-full rounded-none rounded-l-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
      </div>
      <%= link_to suppliers_path, class: "relative -ml-px inline-flex items-center gap-x-1.5 rounded-r-md px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50" do %>
        <%= inline_svg_tag "refresh.svg", class: "-ml-0.5 h-5 w-5 text-gray-400" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/settings/suppliers/_supplier.html.erb
<div class="table-row">
  <div class="table-cell w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-0">
    <%= link_to supplier.name, supplier_path(supplier), class: "text-indigo-600" %>
    <dl class="font-normal lg:hidden">
      <dt class="sr-only"><%= t("tables.cols.phone_number") %></dt>
      <dd class="mt-1 truncate text-gray-700"><%= supplier.phone_number %></dd>
      <dt class="sr-only sm:hidden"><%= t("tables.cols.email_address") %></dt>
      <dd class="mt-1 truncate text-gray-500 sm:hidden"><%= supplier.email_address %></dd>
    </dl>
  </div>
  <div class="hidden lg:table-cell px-3 py-4 text-sm text-gray-500"><%= supplier.phone_number %></div>
  <div class="hidden sm:table-cell px-3 py-4 text-sm text-gray-500"><%= supplier.email_address %></div>
  <div class="table-cell px-3 py-4 text-sm text-gray-500"><%= supplier.contact_person %></div>
  <div class="table-cell py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
    <%= link_to t("actions.edit_record"), edit_supplier_path(supplier), class: "text-indigo-600 hover:text-indigo-900" %>
  </div>
</div>

app/views/settings/suppliers/_tab.html.erb
<% tab_links = [
  NavLink.new(path: suppliers_path, title: t("pages.suppliers"), is_active: true),
  NavLink.new(path: root_path, title: t("pages.clients"), is_active: false)
]
%>

<div>
  <div class="sm:hidden">
    <%= mobile_tab_select tab_links %>
  </div>
  <div class="hidden sm:block">
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex space-x-8" aria-label="Tabs">
        <% tab_links.each do |link| %>
          <%= link_to link.title, link.path, class: "tab-link #{ "tab-link-active" if link.is_active }" %>
        <% end %>
      </nav>
    </div>
  </div>
</div>

app/views/settings/suppliers/_uploads.html.erb
<%# locals: (supplier:, editable: true) -%>

<div class="sm:col-span-4">
  <div class="table min-w-full divide-y divide-gray-300">
    <div class="table-header-group">
      <div class="table-row">
        <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">
          <%= t("tables.cols.title") %>
        </div>
        <div class="table-cell relative py-3.5 pl-3 pr-4 sm:pr-0"></div>
      </div>
    </div>
    <div class="table-row-group border-collapse divide-y divide-gray-200 bg-white">
      <% supplier.uploads.each do |upload| %>
        <div data-controller="upload" class="table-row">
          <div class="table-cell w-full py-2 max-w-0 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none">
            <%= link_to upload.filename, rails_blob_path(upload, disposition: "attachment"), class: "text-indigo-600" %>
          </div>
          <div class="table-cell py-2 text-right text-sm font-medium text-right">
            <% if editable %>
              <%= button_tag t("actions.destroy_record"), type: :button, data: { action: "upload#clear", upload_id_param: "supplier_uploads_#{ upload.id }" }, class: "text-red-600 hover:text-red-900" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/settings/suppliers/edit.html.erb
<% content_for(:title) { @supplier.name } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: suppliers_path, title: t("pages.suppliers")),
      NavLink.new(path: edit_supplier_path(@supplier), title: @supplier.name),
    ]
  } %>
<% end %>

<%= render "form", supplier: @supplier %>

app/views/settings/suppliers/index.html.erb
<% content_for(:title) { t("pages.contragents") } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: suppliers_path, title: t("pages.contragents")),
    ]
  } %>
<% end %>



<div class="px-4 sm:px-6 lg:px-8">
  <%= render "tab" %>
  <div class="sm:mt-8 sm:flex sm:items-center">
    <div class="sm:flex-auto">
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to new_supplier_path, class: "btn-create" do %>
        <%= inline_svg_tag "plus.svg", class: "h-5 w-5" %>
        <%= t("actions.create_record") %>
      <% end %>
    </div>
  </div>
  <div class="-mx-4 mt-4 sm:mt-8 sm:-mx-0">
    <div class="table border-collapse min-w-full divide-y divide-gray-300">
      <div class="table-header-group">
        <div class="table-row">
          <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">
            <%= t("tables.cols.title") %>
          </div>
          <div class="hidden lg:table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
            <%= t("tables.cols.phone_number") %>
          </div>
          <div class="hidden sm:table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
            <%= t("tables.cols.email_address") %>
          </div>
          <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
            <%= t("tables.cols.contact_person") %>
          </div>
          <div class="table-cell relative py-3.5 pl-3 pr-4 sm:pr-0"></div>
        </div>
      </div>
      <div class="table-row-group border-collapse divide-y divide-gray-200 bg-white">
        <%= render @suppliers %>
      </div>
    </div>
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/settings/suppliers/new.html.erb
<% content_for(:title) { t("pages.suppliers") } %>

<% content_for :breadcrumb do %>
  <%= render "layouts/breadcrumb", {
    nav_links: [
      NavLink.new(path: suppliers_path, title: t("pages.suppliers"))
    ]
  } %>
<% end %>

<%= render "form", supplier: @supplier %>